#!/bin/bash
#
#SBATCH --time=01:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --job-name=myjob
#SBATCH --partition=secondary
#SBATCH --output=ptr.log
#SBATCH --gres=gpu:V100
##SBATCH --error=myjob.e%j
##SBATCH --mail-user=yerong2@illinois.edu

#
# End of embedded SBATCH options
#

module load cuda/10.0
conda activate /scratch/yerong/.conda/envs/ptr
bash scripts/run_large_retacred.sh > ptr.log
